# Generated by Django 3.2.3 on 2021-05-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_bookcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C', models.IntegerField(default=0)),
                ('Cplusplus', models.IntegerField(default=0)),
                ('Csharp', models.IntegerField(default=0)),
                ('java', models.IntegerField(default=0)),
                ('python', models.IntegerField(default=0)),
                ('web_frontend', models.IntegerField(default=0)),
                ('web_backend', models.IntegerField(default=0)),
                ('data', models.IntegerField(default=0)),
                ('ML', models.IntegerField(default=0)),
                ('AI', models.IntegerField(default=0)),
                ('database', models.IntegerField(default=0)),
                ('cyber', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
        ),
    ]
