# Generated by Django 3.2.3 on 2021-05-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bookcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookcount',
        ),
    ]
