# Generated by Django 3.2.3 on 2021-05-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_books_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookcount',
        ),
    ]
