# Generated by Django 3.2.3 on 2021-05-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_bookcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('type', models.CharField(blank=True, max_length=150)),
                ('note_name', models.CharField(blank=True, max_length=150)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('u_name', models.CharField(blank=True, max_length=150)),
                ('date_upload', models.DateTimeField(auto_now=True, verbose_name='upload date')),
                ('no_pages', models.CharField(default='no data', max_length=100)),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
