# Generated by Django 3.2.3 on 2021-05-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='id',
        ),
        migrations.AddField(
            model_name='notes',
            name='file_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
