# Generated by Django 3.2.3 on 2021-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210531_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='no_of_notes',
            field=models.IntegerField(default=0),
        ),
    ]
